name: Workflow A

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  store-pr-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR Number
        run: echo "${{ github.event.pull_request.number }}" > pr_number.txt

      - name: Upload PR Number as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-number
          path: pr_number.txt
