name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  process_artifact:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pr_number
          path: ./artifact

      - name: Unzip artifact
        run: |
          unzip ./artifact/pr_number.zip -d ./artifact

      - name: Read PR Number
        id: read-pr-number
        run: |
          PR_NUMBER=$(cat ./artifact/pr_number.txt)
          echo "PR Number: $PR_NUMBER"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_ENV

      - name: Log PR Number
        run: |
          echo "Retrieved PR Number: ${{ env.pr_number }}"
