name: Workflow A

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  store-pr-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the commit from the feature branch (PR head)

      - name: Get PR Number
        run: echo "${{ github.event.pull_request.number }}" > pr_number.txt

      - name: Get Changed Files
        run: |
          # Fetch the base commit SHA for comparison (main branch or base branch)
          BASE_COMMIT=${{ github.event.pull_request.base.sha }}
          HEAD_COMMIT=${{ github.sha }}

          echo "Base commit SHA: $BASE_COMMIT"
          echo "Head commit SHA: $HEAD_COMMIT"

          # Get the list of changed files between base and head commits
          CHANGED_FILES=$(git diff --name-only $BASE_COMMIT $HEAD_COMMIT)

          # Filter files with .c, .cpp, .h, .hpp extensions
          FILTERED_FILES=$(echo "$CHANGED_FILES" | grep -E '\.(c|cpp|h|hpp)$')

          # Save the filtered files to a txt file
          echo "$FILTERED_FILES" > changed_files.txt

      - name: Upload PR Number and Changed Files as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pr-number
          path: pr_number.txt

      - name: Upload Changed Files as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          path: changed_files.txt
