name: List and Echo Artifact Contents

on:
  workflow_run:
    workflows: ["Track PR Number"]  # Replace with your workflow name
    types:
      - completed

jobs:
  list-and-echo-artifact:
    runs-on: ubuntu-latest
    steps:
      # Install GitHub CLI
      - name: Set up GitHub CLI
        run: |
          sudo apt-get install gh

      # List artifacts and get the artifact ID for 'pr-number'
      - name: Get Artifact ID
        id: get-artifact-id
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch the artifact list and find the ID of 'pr-number'
          ARTIFACT_ID=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | select(.name=="pr-number") | .id')
          
          if [ -z "$ARTIFACT_ID" ]; then
            echo "Artifact 'pr-number' not found."
            exit 1
          fi

          echo "Artifact ID for 'pr-number': $ARTIFACT_ID"
          echo "::set-output name=artifact_id::$ARTIFACT_ID"

      # Download and Extract the artifact
      - name: Download and Extract Artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Use the artifact ID from the previous step
          ARTIFACT_ID=${{ steps.get-artifact-id.outputs.artifact_id }}
          gh api repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip > artifact.zip
          
          # Unzip the artifact
          unzip artifact.zip -d artifact_contents

          # Echo the contents of the artifact (assuming it's a text file)
          echo "Contents of the artifact:"
          cat artifact_contents/*
