name: Workflow A

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  store-pr-number:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR Number
        run: echo "${{ github.event.pull_request.number }}" > pr_number.txt

      - name: Get Changed Files
        run: |
          # List all changed files in the PR
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

          # Filter files with .c, .cpp, .h, .hpp extensions
          FILTERED_FILES=$(echo "$CHANGED_FILES" | grep -E '\.(c|cpp|h|hpp)$')

          # Save the filtered files to a txt file
          echo "$FILTERED_FILES" > changed_files.txt

      - name: Upload PR Number as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-number
          path: pr_number.txt

      - name: Upload Changed Files as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          path: changed_files.txt
