name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  process_artifact:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-number  # This should match the artifact name from Workflow A
          path: ./artifact

      - name: Unzip the artifact
        run: |
          unzip ./artifact/pr-number.zip -d ./artifact  # Unzips the artifact to ./artifact folder

      - name: Read and Echo PR Number
        run: |
          # Access the pr_number.txt file from the unzipped folder and echo its contents
          PR_NUMBER=$(cat ./artifact/pr_number.txt)
          echo "PR Number: $PR_NUMBER"
