name: List Artifacts

on:
  workflow_run:
    workflows: ["Track PR Number"]  # Trigger on completion of another workflow (can be changed)
    types:
      - completed

jobs:
  list-artifacts:
    runs-on: ubuntu-latest
    steps:
      # Install GitHub CLI
      - name: Set up GitHub CLI
        run: |
          sudo apt-get install gh

      # List artifacts available in the repository
      - name: List Artifacts
        env:
          GH_TOKEN: ${{ github.token }}  # Use GitHub token for authentication
        run: |
          # Fetch the list of artifacts
          ARTIFACTS=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[].name')
          
          # Check if there are any artifacts and echo the list
          if [ -z "$ARTIFACTS" ]; then
            echo "No artifacts found."
          else
            echo "Available artifacts:"
            echo "$ARTIFACTS"
          fi
