name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  process_artifact:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-number  # Artifact name used in Workflow A
          path: ./artifact

      - name: Unzip artifact
        run: |
          unzip ./artifact/pr-number.zip -d ./artifact  # Unzips the artifact

      - name: Read and Echo PR Number
        run: |
          # Read the contents of the pr_number.txt file and echo it
          PR_NUMBER=$(cat ./artifact/pr_number.txt)
          echo "PR Number: $PR_NUMBER"
