name: Workflow B

on:
  workflow_run:
    workflows: ["Workflow A"]
    types:
      - completed

jobs:
  process_artifact:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: pr-number  # This must match the artifact name from Workflow A
          path: ./artifact

      - name: Read and Echo PR Number
        run: |
          # Directly access the pr_number.txt file
          PR_NUMBER=$(cat ./artifact/pr_number.txt)
          echo "PR Number: $PR_NUMBER"
