name: List and Echo Artifact Contents

on:
  workflow_run:
    workflows: ["Track PR Number"]  # Trigger on completion of another workflow (can be changed)
    types:
      - completed

jobs:
  list-and-echo-artifact:
    runs-on: ubuntu-latest
    steps:
      # Install GitHub CLI
      - name: Set up GitHub CLI
        run: |
          sudo apt-get install gh

      # List artifacts available in the repository
      - name: List Artifacts
        env:
          GH_TOKEN: ${{ github.token }}  # Use GitHub token for authentication
        run: |
          # Fetch the list of artifacts
          ARTIFACTS=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[].name')
          
          # Check if there are any artifacts and echo the list
          if [ -z "$ARTIFACTS" ]; then
            echo "No artifacts found."
          else
            echo "Available artifacts:"
            echo "$ARTIFACTS"
          fi

      # Download the artifact (replace "pr-number" with the artifact name you want)
      - name: Download and Echo Artifact Contents
        env:
          GH_TOKEN: ${{ github.token }}  # Use GitHub token for authentication
        run: |
          # Replace 'pr-number' with the name of your artifact
          ARTIFACT_NAME="pr-number" 
          
          # Download the artifact
          echo "Downloading artifact $ARTIFACT_NAME"
          gh api repos/${{ github.repository }}/actions/artifacts/${ARTIFACT_NAME}/zip --output artifact.zip
          
          # Unzip the downloaded artifact
          unzip artifact.zip -d artifact_contents

          # Echo the contents of the artifact (assuming it's a txt file)
          echo "Contents of the artifact:"
          cat artifact_contents/*  # Assuming there's only one file in the artifact
